apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-error-rate-check
  namespace: dev
spec:
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] < 0.05
    failureLimit: 1
    # İŞTE ARADIĞIMIZ MÜHENDİSLİK ÇÖZÜMÜ:
    failOnEmpty: true 
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: sum(rate(http_requests_total{status=~"5.*"}[1m]))
