apiVersion: argoproj.io/v1alpha1 # Argo Rollouts API'si
kind: Rollout
metadata:
  name: auth-service
  namespace: dev
spec:
  replicas: 4 # Kademeli geçişi net görebilmek için replica sayısını 4 yapıyoruz
  strategy:
    canary:
      # İstediğin kademeli açılım adımları: %10 -> %30 -> %50 -> %100
      steps:
      - setWeight: 10
      - pause: { duration: 20s } # 20 saniye gözlemle
      - setWeight: 30
      - pause: { duration: 20s }
      - setWeight: 50
      - pause: {} # Manuel onay için süresiz duraklama (Bölüm B-2'de Prometheus ile otomatize edeceğiz)
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:alpine
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
