apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth-service
  namespace: dev
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 10
      # İŞTE YENİ KALİTE KAPIMIZ: %10'u bastıktan sonra dur. Bu analiz bitmeden %30'a geçmek yasak!
      - analysis:
          templates:
          - templateName: http-error-rate-check
      - setWeight: 30
      - pause: { duration: 20s }
      - setWeight: 50
      - pause: { duration: 30s }
      - setWeight: 100
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:alpine
        env:
        - name: APP_VERSION
          value: "v7" # Yeni revizyonu fırlatıyoruz
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
