apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-order-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/berke44gulec/gitops-infrastructure.git'
    targetRevision: HEAD
    path: environments/dev/services/order
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
