apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payment-service
  namespace: dev
spec:
  replicas: 2
  strategy:
    blueGreen:
      # Canlı trafiğin aktığı asıl servis
      activeService: payment-service-active
      # Yeni sürümün test edileceği arka kapı servisi
      previewService: payment-service-preview
      # Yeni sürüm başarılı olsa bile biz onay vermeden canlıya geçmesin
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:alpine
        env:
        - name: APP_VERSION
          value: "v2"
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
# 1. CANLI SERVİS (Blue)
apiVersion: v1
kind: Service
metadata:
  name: payment-service-active
  namespace: dev
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
# 2. ÖNİZLEME/TEST SERVİSİ (Green)
apiVersion: v1
kind: Service
metadata:
  name: payment-service-preview
  namespace: dev
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
